#!/bin/bash
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08p1.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08p2.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08p3.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08sp.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08sa.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08s.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08t.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08111.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08112.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08113.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08121.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08122.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08123.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08131.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08132.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08133.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08211.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08212.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08213.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08221.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08222.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08223.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08231.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08232.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08233.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08311.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08312.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08313.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08321.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08322.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08323.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08331.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08332.py --gpus '0'
python examples/run.py -c examples/STEMLP/STEMLP_PEMS08333.py --gpus '0'



